config/routes.rb
Rails.application.routes.draw do

  resources :recipes

  resources :partners

  resources :password_resets, only: [:new, :create, :edit, :update]

  root  'static_pages#products'

  get   'uses', to: 'recipes#index'

  get   'about', to: 'static_pages#about'

  get   'locations',  to:  'partners#index', as: 'locations'

  get   'contact', to: 'messages#new', as: 'contact'

  post  'contact', to: 'messages#create'

  get   'namoy_manejo_contenido', to: 'user_sessions#new'

  post  'namoy_manejo_contenido', to: 'user_sessions#create'

  delete 'logout', to: 'user_sessions#destroy'

  

end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :subject, :message
  validates  :name, :email, :subject, :message, presence: true
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  mount_uploader :logo, ImageUploader
  validates  :name, :country, :city, :logo, presence: true
  validates :name, length: { maximum: 17 }
  validates :country, length: { maximum: 11 }
  validates :city, length: { maximum: 8 }

  def image_name
    logo.to_s.split('/')[-1]
  end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  validates  :name, :time_ready, :quantity, :flavor, :ingredients, :instructions, :image, presence: true
  validates :name, length: { maximum: 41 }
  validates :time_ready, length: { maximum: 15 }
  validates :quantity, length: { maximum: 12 }

  def string_to_array(paragraph) #intended for breaking the string into lines
    paragraph.split("\n")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, :name, presence: true
  validates :email, uniqueness: true
  before_save :downcase_email

  def downcase_email
    email.downcase!
  end

  def generate_password_reset_token!
    update_attribute(:password_reset_token, SecureRandom.urlsafe_base64(48))
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private

  def logged_in?
    current_user
  end
  helper_method :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    if current_user
      true
    else
      redirect_to namoy_manejo_contenido_path, notice: "Para ver esa página debes iniciar sesión"
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.message_me(@message).deliver_now
      redirect_to locations_path, notice: "Gracias por escribirnos."
    else
      flash[:alert] = "No se pudo enviar el mensaje. Por favor intenta de nuevo."
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :subject, :message)
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :require_user, only: [:show, :new, :edit]
  before_action :set_partner, only: [:show, :edit, :update, :destroy]

  def index
    @partners = Partner.all
  end

  def show

  end

  def new
    @partner = Partner.new
  end

  def edit
  end

  def create
    @partner = Partner.new(partner_params)

    if @partner.save
      flash[:success] = "Un nuevo distribuidor ha sido creado"
      redirect_to @partner
    else
      render :new
    end
  end

  def update
    if @partner.update(partner_params)
      flash[:success] = "El distribuidor ha sido actualizado"
      redirect_to @partner
    else
      render :edit
    end
  end

  def destroy
    @partner.destroy
    redirect_to partners_url, notice: 'El distribuidor ha sido eliminado'
  end

  private

    def set_partner
      @partner = Partner.find(params[:id])
    end

    def partner_params
      params.require(:partner).permit(:name, :country, :city, :logo, :instagram, :facebook, :website)
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user
      user.generate_password_reset_token!
      MessageMailer.password_reset(user).deliver_now
      redirect_to namoy_manejo_contenido_path
      flash[:success] = "Te hemos enviado un email para restablecer tu contraseña."
    else
      flash.now[:error] = "No tenemos un usuario con ese email."
      render :new
    end
  end

  def edit
    @user = User.find_by(password_reset_token: params[:id])

    if @user
    else
      render file: 'public/404.html', status: :not_found
    end
  end

  def update
    @user = User.find_by(password_reset_token: params[:id])
    if @user && @user.update_attributes(user_params)
      @user.update_attribute(:password_reset_token, nil)
      session[:user_id] = @user.id
      flash[:success] = "La contraseña ha sido restablecida."
      redirect_to root_path
    else
      flash.now[:error] = "No hemos encontrado el token para restablecer la contraseña."
      render :edit
    end 
  end

  private
  
  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:new, :edit]

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def edit
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      flash[:success] = "Tu nueva receta ha sido creada"
      redirect_to @recipe
    else
      render :new
    end
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe, notice: "La receta ha sido modificada"
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_url, notice: 'La receta ha sido eliminada'
  end

  private
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:name, :time_ready, :quantity, :flavor, :ingredients, :instructions, :image)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def products
  end

  def uses
  end

  def about
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Has iniciado sesión en el sistema de manejo de contenido de Namoy"
      redirect_to root_path
    else
      flash[:error] = "Por favor revisa tu usuario y contraseña e intenta de nuevo"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    reset_session
    redirect_to namoy_manejo_contenido_path, notice: "Tu sesión ha terminado"
  end
end

app/views/layouts/_footer.html.erb
<!-- FOOTER -->
<div class="container marketing">
  <footer>
    <hr class="separator">
    <div class="row">
      <div class="col-md-6">
        <ul class="contact-info">
          <li>
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>&nbsp;&nbsp;
            <a href="mailto:info@namoy.co">info@namoy.co</a>
          </li>
          <li><span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>&nbsp;&nbsp;(57) 313 829 0971</li>
        </ul><!-- /.contact-info -->
      </div><!-- /.col-md-6 -->
      <div class="col-md-6">
        <ul class="social-links">
          <li>
            <%= link_to '<i class="fa fa-facebook-square fa-2x"></i>'.html_safe, 
                        "https://www.facebook.com/namoynatural", 
                        :target => "_blank" %>
          </li>
          <li>
            <%= link_to '<i class="fa fa-twitter-square fa-2x"></i>'.html_safe,
                        "https://twitter.com/search?q=%40NAMOYrealfoods&src=typd", 
                        :target => "_blank" %>
          </li>
          <li>
            <%= link_to '<i class="fa fa-instagram fa-2x"></i>'.html_safe, 
                        "https://www.instagram.com/namoy_realfoods", 
                        :target => "_blank" %>
          </li>
          <li>
            <%= link_to '<i class="fa fa-google-plus-square fa-2x"></i>'.html_safe,
                        "#", 
                        :target => "_blank" %>
          </li>
        </ul><!-- /.social-links -->
      </div><!-- /.col-md-6 -->
      <div class="row">
        <div class="col-md-12">
          <p id="copyright">&copy; 2016 NA-MOY</p>
        </div><!-- /.col-md-12 -->
      </div><!-- /.row -->
    </div><!-- /.row -->
  </footer>
</div><!-- /.container -->

app/views/layouts/_header.html.erb
<!-- NAVBAR
================================================== -->
<div class="navbar-wrapper">
  <div class="container">
    <nav class="navbar navbar-default transparent navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to image_tag("logo_blanco_letras.png", size: "94x30", alt: "Logo Namoy"), root_path, class: "navbar-brand", id: "logo" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li id="small-link"><%= link_to "Logout", logout_path, method: :delete %></li>
            <% end %>
            <li><%= link_to "Productos", root_path %></li>
            <li><%= link_to "Usos", uses_path %></li>
            <li><%= link_to "Encuéntranos", locations_path %></li>
            <li><%= link_to "Nosotros", about_path %></li>
            <!-- <li class="dropdown" id="language">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span id="language">esp<span class="caret"></span></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">esp</a></li>
                <li><a href="#">eng</a></li>        
              </ul>
            </li> -->
          </ul>
        </div>
      </div>
    </nav>
  </div>
</div>

app/views/messages/new.html.erb
<div class="jumbotron secontron">
  <div class="container marketing">
    <h1 class="namoy-font">Escríbenos</h1>
  </div>
</div><!-- /.container -->


<div class="container marketing">
  <div class="row">
    <div class="col-lg-12">
      <h2 class="center"> 
        Comparte con nosotros tus dudas, sugerencias y experiencias.
      </h2>
    </div><!-- /.col-lg-12 -->
  </div><!-- /.row -->
  <hr class="underline"> 
  


<!-- Content
================================================== -->
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="form-container">
      <%= form_for @message, url: contact_path do |f| %>
        <% if @message.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= "#{pluralize(@message.errors.count, "error")} prohibited this message from being sent:" %>
            </h2>

            <ul>
              <% @message.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <p class="notice"><%= flash[:notice] %></p>

        <h1 class="contitle center"><i class="fa fa-envelope-o fa-2x orange"></i></h1>

        <hr class="orange">

        <div class="form-group">
          <%= f.label :name, "Nombre", class: "lead" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :email, class: "lead" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :subject, "Asunto", class: "lead" %>
          <%= f.text_field :subject, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :message, "Mensaje", class: "lead" %>
          <%= f.text_area :message, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.submit 'Enviar', class: "btn btn-lg btn-primary", role: "button" %>
        </div>
      <% end %>
      </div><!-- /.form-conteiner -->
    </div><!-- /.col-md-4 -->
    <div class="col-md-4"></div>
  </div><!-- /.row -->
  <p class="page-links"><%= link_to 'Ir a "Encuéntranos"', partners_path, class: "recipe-link" %></p>
</div><!-- /.container -->

app/views/partners/edit.html.erb
 <div class="jumbotron secontron" id="usesjumbo">
  <div class="container marketing">
    <h1 class="namoy-font">Edita este distribuidor</h1>
  </div>
</div><!-- /.container -->

<div class="container marketing">
  <%= render 'form' %>
  <p class="page-links">
    <%= link_to 'Ir a distribuidores', partners_path, class: "recipe-link" %> <span class="orange">|</span> 
    <%= link_to 'Volver', @partner, class: "recipe-link" %>
  </p>
</div><!-- /.container -->

app/views/partners/index.html.erb
<div class="jumbotron secontron" id="back-encuentranos">
  <div class="container marketing">
    <h1 class="namoy-font">Encuéntranos</h1>
  </div>
</div><!-- /.container -->

<% flash.each do |type, message| %>
  <div class="alert flash <%= type %>">
    <%= message %>
  </div>
<% end %>

<div class="container marketing">  
  <div class="row">
    <div class="col-lg-12">
      <h2 class="center"> 
        <span class="glyphicon glyphicon-map-marker orange smaller-text" aria-hidden="true"></span> 
        Encuentra nuestros productos en alguno de estos lugares 
        <span class="glyphicon glyphicon-map-marker orange smaller-text" aria-hidden="true"></span>
      </h2>
    </div><!-- /.col-lg-12 -->
  </div><!-- /.row -->
  <hr class="underline"> 

  <div class="row">  
    <p id="notice"><%= notice %></p>
    <% if @partners.size > 0 %>
      <% @partners.each do |partner| %>
        <div class="col-sm-6 col-md-3">
          <div class="thumbnail">
            <%= image_tag partner.logo, alt: partner.name, class: "featurette-image img-responsive center-block" %> 
            <!-- https://unsplash.it/800/500?image=312 -->
            <div class="caption">
              <h3 class="thumbnail-name"><%= partner.name %></h3>
              <p class="lead partner-info">País: <%= partner.country %></p>
              <p class="lead partner-info">Ciudad: <%= partner.city %></p>
              <ul id="partner-social">
                <li>
                  <%= link_to '<i class="fa fa-instagram fa-2x"></i>'.html_safe, 
                              partner.instagram, 
                              :target => "_blank" %>
                </li>
                <li>
                  <%= link_to '<i class="fa fa-facebook-square fa-2x"></i>'.html_safe, 
                              partner.facebook, 
                              :target => "_blank" %>
                </li>
                <% unless partner.website.blank? %>
                  <li>
                    <%= link_to '<i class="fa fa-globe fa-2x"></i>'.html_safe, 
                                partner.website, 
                                :target => "_blank" %>
                  </li>
                <% end %>
              </ul><!-- /.social-links -->
              <% if logged_in? %>
                <p class="enlaces"><%= link_to 'Ver distribuidor', partner %></p>
              <% end %>
            </div><!-- /.caption -->
          </div><!-- /.thumbnail -->
        </div><!-- /.col-sm-6 -->
      <% end %>
    <% else %>
      <div class="col-md-12">
        <p class="with-border">
          Dentro de poco encontrarás a todos nuestros distribuidores en este espacio.
        </p>
      </div>
    <% end %>   
  </div><!-- /.row -->

  <% if logged_in? %>
    <p class="page-links"><%= link_to 'Agregar distribuidor', new_partner_path, class: "new-recipe-link" %></p>
  <% end %>

  <div class="row">
    <div class="col-md-3 col-sm-2 col-xs-1"></div>
    <div class="col-md-6 col-sm-8 col-xs-10 with-border" id="contact-box">
      <p class="center lead partner-info">
        Escríbenos si tienes dudas, sugerencias o simplemente quieres compartirnos tu experiencia con nuestros productos.
      </p>
      <p id="center-button">
        <a class="btn btn-primary btn-lg" href="/contact" role="button">Escríbenos</a>
      </p>
      <br />
    </div><!-- /.col-lg-12 -->
    <div class="col-md-3 col-sm-2 col-xs-1"></div>
  </div><!-- /.row -->
  
</div><!-- /.container -->

app/views/partners/new.html.erb
<div class="jumbotron secontron" id="usesjumbo">
  <div class="container marketing">
    <h1 class="namoy-font">Agrega un distribuidor</h1>
  </div>
</div><!-- /.container -->

<div class="container marketing">
  <%= render 'form' %>
  <p class="page-links"><%= link_to 'Ir a "Encuéntranos"', partners_path, class: "new-recipe-link" %></p>
</div><!-- /.container -->

app/views/partners/show.html.erb
<div class="jumbotron secontron" id="usesjumbo">
  <div class="container marketing">
    <h1 class="namoy-font smaller-title"><%= @partner.name %></h1>
  </div>
</div><!-- /.container -->


<div class="container marketing">

  <ul class="ideas partner-show lead">
    <li><%= image_tag @partner.logo, alt: @partner.name + " logo" , class: "featurette-image img-responsive" %></li>
    <li><strong>Imagen actual:</strong> <%= @partner.image_name %></li>
    <li><strong>País:</strong> <%= @partner.country %></li>
    <li><strong>Ciudad:</strong> <%= @partner.city %></li>
    <li><strong>Instagram:</strong> <%= @partner.instagram %></li>
    <li><strong>Facebook:</strong> <%= @partner.facebook %></li>
    <li><strong>Website:</strong> <%= @partner.website %></li>
  </ul>

  <p class="page-links">
    <%= link_to 'Ir a "Encuéntranos"', partners_path, class: "recipe-link" %> <span class="orange">|</span> 
    <%= link_to 'Editar', edit_partner_path(@partner), class: "recipe-link" %> <span class="orange">|</span>  
    <%= link_to 'Eliminar distribuidor', @partner, method: :delete, data: { confirm: '¿Seguro que quieres eliminar este distribuidor?' }, class: "recipe-link" %>
  </p>
</div><!-- /.container -->

app/views/password_resets/edit.html.erb
<div class="jumbotron secontron">
  <div class="container marketing">
    <h1 class="namoy-font">Elige tu nueva contraseña</h1>
  </div>
</div><!-- /.container -->

<div class="container marketing">
    <!-- Form
  ================================================== -->
  <div class="row featurette create-form">
    <div class="col-md-2"></div><!-- /.col-md-2 -->
    <div class="col-md-8">
      <div class="form-container">
      <%= form_for @user, url: password_reset_path(@user.password_reset_token), html: { method: :patch } do |f| %>
        <p>
        <% flash.each do |type, message| %>
          <div class="alert flash <%= type %>">
            <%= message %>
          </div>
        <% end %>
        </p>
        
        <div class="form-group">
          <%= f.label :password, "Nueva Contraseña", class: "lead" %>
          <%= f.password_field :password, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation, "Nueva Contraseña (otra vez)", class: "lead" %>
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
    
        <div class="form-group">
          <%= submit_tag "Cambiar mi contraseña", class: "btn btn-lg btn-primary", role: "button" %>
        </div>
      <% end %>
      </div><!-- /.form-container -->
    </div><!-- /.col-md-5 -->
    <div class="col-md-2"></div><!-- /.col-md-2 -->
  </div><!-- /.row -->


</div><!-- /.container -->

app/views/password_resets/new.html.erb
<div class="jumbotron secontron">
  <div class="container marketing">
    <h1 class="namoy-font">Restablecer mi contraseña</h1>
  </div>
</div><!-- /.container -->

<div class="container marketing">
    <!-- Form
  ================================================== -->
  <div class="row featurette create-form">
    <div class="col-md-2"></div><!-- /.col-md-2 -->
    <div class="col-md-8">
      <div class="form-container">
      <%= form_tag password_resets_path do %>
        <p>
        <% flash.each do |type, message| %>
          <div class="alert flash <%= type %>">
            <%= message %>
          </div>
        <% end %>
        </p>
        
        <div class="form-group">
          <%= label_tag :email, "Email", class: "lead" %>
          <%= text_field_tag :email %>
        </div>
  
        <div class="form-group">
          <%= submit_tag "Enviar", class: "btn btn-lg btn-primary", role: "button" %>
        </div>
      <% end %>
      </div><!-- /.form-container -->
    </div><!-- /.col-md-5 -->
    <div class="col-md-2"></div><!-- /.col-md-2 -->
  </div><!-- /.row -->


</div><!-- /.container -->

app/views/recipes/edit.html.erb
<div class="jumbotron secontron" id="usesjumbo">
  <div class="container marketing">
    <h1 class="namoy-font">Edita tu receta</h1>
  </div>
</div><!-- /.container -->

<div class="container marketing">
  <%= render 'form' %>
  <p class="page-links">
    <%= link_to 'Ir a recetas', recipes_path, class: "recipe-link" %> <span class="orange">|</span> 
    <%= link_to 'Volver', @recipe, class: "recipe-link" %>
  </p>
</div><!-- /.container -->

app/views/recipes/new.html.erb
<div class="jumbotron secontron" id="usesjumbo">
  <div class="container marketing">
    <h1 class="namoy-font">Agrega una receta</h1>
  </div>
</div><!-- /.container -->

<div class="container marketing">
  <%= render 'form' %>
  <p class="page-links"><%= link_to 'Ir a recetas', recipes_path, class: "recipe-link" %></p>
</div><!-- /.container -->

app/views/recipes/show.html.erb
<% content_for :head do %>
  <meta property="og:url"           content="<%= "http://www.namoy.co" + recipe_path(@recipe) %>" />
  <meta property="og:type"          content="website" />
  <meta property="og:title"         content="NA-MOY - <%= @recipe.name %>" />
  <meta property="og:description"   content="Receta para preparar <%= @recipe.name %> usando NA-MOY panela en polvo" />
  <meta property="og:image"         content="<%= @recipe.image.url %>" />
<% end %>

<% content_for :body do %>
  <div id="fb-root"></div>
  <script>
    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/es_LA/sdk.js";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>
<% end %>

<div class="jumbotron secontron" id="usesjumbo">
  <div class="container marketing">
    <h1 class="namoy-font smaller-title"><%= @recipe.name %></h1>
  </div>
</div><!-- /.container -->

<div class="container marketing">

  <div class="row">
    <div class="col-md-12 share">
      <div class="fb-share-button white" data-href="<%= "http://www.namoy.co" + recipe_path(@recipe) %>" data-layout="button" data-size="large" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore lead" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fwww.namoy.co%2Frecipes%2F<%= recipe_path(@recipe).split('/').pop %>&amp;src=sdkpreparse"><i class="fa fa-facebook-square"></i> compartir</a></div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <p class="lead">Tiempo de preparación: <%= @recipe.time_ready %></p>
      <p class="lead">Cantidad: <%= @recipe.quantity %></p>
      <h2 class="<%= @recipe.flavor %>-color subtitle">Ingredientes</h2>
      <hr class="underline">
      <p> 
        <ul class="ideas lead">
        <% @recipe.string_to_array(@recipe.ingredients).each do |ingredient| %>
          <li class="ing">
            <span class="glyphicon glyphicon-grain <%= @recipe.flavor %>-color" aria-hidden="true"></span> 
            <%= ingredient %>
          </li>
        <% end %>
        </ul>
      </p>
      <h2 class="<%= @recipe.flavor %>-color subtitle">Instrucciones</h2>
      <hr class="underline">
      <p> 
        <ul class="ideas lead">
        <% @recipe.string_to_array(@recipe.instructions).each do |instruction| %>
          <li class="ing just">
            <span class="glyphicon glyphicon-grain <%= @recipe.flavor %>-color" aria-hidden="true"></span> 
            <%= instruction %>
          </li>
        <% end %>
        </ul>
      </p>
    </div><!-- /.col-lg-12 -->
  </div><!-- /.row -->

  <p class="page-links">
    <%= link_to 'Ir a "Usos"', recipes_path, class: "recipe-link" %>
    <% if logged_in? %>
      <span class="orange"> |</span> 
      <%= link_to 'Editar', edit_recipe_path(@recipe), class: "recipe-link" %><span class="orange"> |</span>  
      <%= link_to 'Eliminar receta', @recipe, method: :delete, data: { confirm: '¿Seguro que quieres eliminar esta receta?' }, class: "recipe-link" %>
    <% end %>
  </p>
</div><!-- /.container -->

app/views/static_pages/locations.html.erb
<div class="jumbotron secontron" id="locajumbo">
  <div class="container marketing">
    <h1 class="namoy-font">Encuéntranos</h1>
  </div>
</div><!-- /.container -->

app/views/static_pages/store.html.erb
<h1>StaticPages#store</h1>
<p>Find me in app/views/static_pages/store.html.erb</p>

app/views/user_sessions/new.html.erb
<div class="jumbotron secontron">
  <div class="container marketing">
    <h1 class="namoy-font">Manejo de contenido</h1>
  </div>
</div><!-- /.container -->

<div class="container marketing">
  <!-- Form
================================================== -->
<div class="row featurette create-form">
  <div class="col-md-2"></div><!-- /.col-md-2 -->
  <div class="col-md-8">
    <div class="form-container">
    <%= form_tag namoy_manejo_contenido_path do %>
      <p>
        <% flash.each do |type, message| %>
          <div class="alert flash <%= type %>">
            <%= message %>
          </div>
        <% end %>
      </p>

      <div class="form-group">
        <%= label_tag :email, "Email", class: "lead" %>
        <%= text_field_tag :email, params[:email] %>
      </div>
      <!-- , class: "form-control" -->
      <!-- , class: "form-control" -->
      <div class="form-group">
        <%= label_tag :password, "Contraseña", class: "lead" %>
        <%= password_field_tag :password %>
      </div>

      <div class="form-group">
        <%= submit_tag 'Iniciar Sesión', class: "btn btn-lg btn-primary", role: "button" %>   
        <%= link_to "Olvidé mi contraseña", new_password_reset_path, class: "lead", id: "forgot-link" %>
      </div>
    <% end %>
    </div><!-- /.form-container -->
  </div><!-- /.col-md-5 -->
  <div class="col-md-2"></div><!-- /.col-md-2 -->
</div><!-- /.row -->


</div><!-- /.container -->